# -*- coding: utf-8 -*-
"""FeatureSelection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnrNgm6a3ubWCMZpiBjYBTG-IZIsCnxX
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = "/content/drive/MyDrive/code"
print(os.listdir(BASE_PATH))

['B.dat', 'C.dat', 'D.dat', 'E.dat',
 'Status_Kelmarsh_1_2019-01-01_2020-01-01_228.csv',
 'Status_Kelmarsh_2_2019-01-01_2020-01-01_229.csv',
 ...]

import numpy as np

C = np.loadtxt("/content/drive/MyDrive/code/C.dat")
D = np.loadtxt("/content/drive/MyDrive/code/D.dat")
E = np.loadtxt("/content/drive/MyDrive/code/E.dat")
B = np.loadtxt("/content/drive/MyDrive/code/B.dat")

print(C.shape, D.shape, E.shape, B.shape)

import os

BASE_PATH = "/content/drive/MyDrive/code"
for f in os.listdir(BASE_PATH):
    if "Status_Kelmarsh_1" in f:
        print(f)

import glob
import pandas as pd

BASE_PATH = "/content/drive/MyDrive/code"

kelmarsh_files = glob.glob(
    BASE_PATH + "/Status_Kelmarsh_*_2019-01-01_*_2020-01-01_*.csv"
)

print("Files found:", len(kelmarsh_files))
for f in kelmarsh_files:
    print(f)

import pandas as pd

def read_kelmarsh_csv(file):
    return pd.read_csv(
        file,
        engine="python",        # REQUIRED
        sep=",",                # default delimiter
        encoding="utf-8",
        on_bad_lines="skip"     # skip corrupted rows safely
    )

kel_df = pd.concat(
    [read_kelmarsh_csv(f) for f in kelmarsh_files],
    axis=0,
    ignore_index=True
)

print("Kelmarsh SCADA shape:", kel_df.shape)

def read_kelmarsh_csv(file):
    return pd.read_csv(
        file,
        engine="python",
        sep=";",
        encoding="utf-8",
        on_bad_lines="skip"
    )

kel_df.head()

print(kel_df.columns.tolist())

['TimeStamp', 'WindSpeed', 'RotorSpeed', 'GeneratorSpeed',
 'PitchAngle', 'YawAngle', 'Torque', 'ActivePower', ...]

features = ["WindSpeed","RotorSpeed","GeneratorSpeed",
            "PitchAngle","YawAngle","Torque"]
target = "ActivePower"

print("Total columns:", len(kel_df.columns))
for c in kel_df.columns:
    print(c)

def find_column(keyword, columns):
    matches = [c for c in columns if keyword.lower() in c.lower()]
    if len(matches) == 0:
        raise ValueError(f"No column found for keyword: {keyword}")
    return matches[0]

print(kel_df.columns.tolist())

# ------------------------------------------------------------
# AUTO IDENTIFICATION OF KELMARSH SCADA COLUMNS
# ------------------------------------------------------------

def find_column(keyword, columns):
    """Find first column containing the keyword (case-insensitive)."""
    matches = [c for c in columns if keyword.lower() in c.lower()]
    if len(matches) == 0:
        raise ValueError(f"No column found for keyword: '{keyword}'")
    return matches[0]

# Print all columns once (for transparency)
print("\n--- ALL AVAILABLE COLUMNS ---")
for col in kel_df.columns:
    print(col)

import numpy as np
from sklearn.feature_selection import mutual_info_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score


class MI_AMO_BHS:
    """
    MI-AMO-BHS: Two-stage hybrid feature selection model
    Stage 1: Mutual Information filtering
    Stage 2: Adaptive Multi-Objective Binary Harmony Search
    """

    def __init__(self, beta=0.6, hms=20, max_iter=100,
                 n_min=5, n_max=None, random_state=42):
        self.beta = beta
        self.hms = hms
        self.max_iter = max_iter
        self.n_min = n_min
        self.n_max = n_max
        self.random_state = random_state
        np.random.seed(random_state)

    # --------------------------------------------------
    # MAIN PIPELINE
    # --------------------------------------------------
    def fit(self, X, y, verbose=1):

        # ===============================
        # STAGE 1: MI FILTERING (Eq. 8–14)
        # ===============================
        if verbose:
            print("Stage 1: Mutual Information Filtering")

        mi_scores = mutual_info_regression(
            X, y,
            discrete_features=False,
            n_neighbors=3,
            random_state=self.random_state
        )

        ranked_idx = np.argsort(mi_scores)[::-1]          # Eq. 10
        n_retain = max(1, int(np.ceil(self.beta * X.shape[1])))
        self.selected_stage1_ = ranked_idx[:n_retain]     # Eq. 11–12
        X_filt = X[:, self.selected_stage1_]

        if verbose:
            print(f"  Features reduced: {X.shape[1]} → {n_retain}")

        # =========================================
        # STAGE 2: AMO-BHS OPTIMIZATION (Eq. 15–30)
        # =========================================
        if verbose:
            print("\nStage 2: AMO-BHS Optimization")

        n_features = X_filt.shape[1]
        n_max = self.n_max if self.n_max else n_features

        # Harmony Memory Initialization (Algorithm 1)
        HM = np.zeros((self.hms, n_features), dtype=int)
        for i in range(self.hms):
            k = np.random.randint(self.n_min, n_max + 1)
            HM[i, np.random.choice(n_features, k, replace=False)] = 1

        fitness = [self._evaluate(h, X_filt, y) for h in HM]

        # Main Optimization Loop
        for it in range(self.max_iter):

            # Adaptive parameters (Eq. 23–24)
            HMCR = 0.7 + 0.25 * (it / self.max_iter) ** 2
            PAR = 0.5 * np.exp(-3 * it / self.max_iter)

            new_harmony = np.zeros(n_features, dtype=int)

            for j in range(n_features):
                if np.random.rand() < HMCR:
                    new_harmony[j] = HM[np.random.randint(self.hms), j]
                    if np.random.rand() < PAR:
                        new_harmony[j] = 1 - new_harmony[j]
                else:
                    new_harmony[j] = np.random.randint(2)

            # Constraint Repair (Eq. 21–22)
            count = new_harmony.sum()
            if count < self.n_min:
                zeros = np.where(new_harmony == 0)[0]
                new_harmony[np.random.choice(
                    zeros, self.n_min - count, replace=False)] = 1
            elif count > n_max:
                ones = np.where(new_harmony == 1)[0]
                new_harmony[np.random.choice(
                    ones, count - n_max, replace=False)] = 0

            new_fit = self._evaluate(new_harmony, X_filt, y)
            worst = self._find_worst(fitness)

            if self._dominates(new_fit, fitness[worst]):
                HM[worst] = new_harmony
                fitness[worst] = new_fit

            if verbose and (it + 1) % 20 == 0:
                best_rmse = min(f[0] for f in fitness)
                print(f"  Iter {it+1}: Best RMSE = {best_rmse:.4f}")

        # Pareto Front Extraction (Eq. 30)
        self.pareto_front_ = []
        self.pareto_fitness_ = []
        for i in range(self.hms):
            if not any(self._dominates(fitness[j], fitness[i])
                       for j in range(self.hms) if j != i):
                self.pareto_front_.append(HM[i])
                self.pareto_fitness_.append(fitness[i])

        if verbose:
            print("\nPareto front size:", len(self.pareto_front_))

        return self

    # --------------------------------------------------
    # FITNESS FUNCTION (Eq. 19)
    # --------------------------------------------------
    def _evaluate(self, harmony, X, y):
        idx = np.where(harmony == 1)[0]
        if len(idx) == 0:
            return (1e6, 1.0)

        model = RandomForestRegressor(
            n_estimators=100,
            max_depth=10,
            random_state=self.random_state,
            n_jobs=-1
        )

        scores = cross_val_score(
            model, X[:, idx], y,
            cv=5,
            scoring='neg_mean_squared_error',
            n_jobs=-1
        )

        rmse = np.sqrt(-np.mean(scores))
        feature_ratio = len(idx) / len(harmony)

        return rmse, feature_ratio

    # --------------------------------------------------
    # PARETO OPERATORS
    # --------------------------------------------------
    def _dominates(self, f1, f2):
        return all(a <= b for a, b in zip(f1, f2)) and any(a < b for a, b in zip(f1, f2))

    def _find_worst(self, fitness):
        dom_count = [sum(self._dominates(fitness[j], fitness[i])
                         for j in range(len(fitness)))
                     for i in range(len(fitness))]
        return np.argmax(dom_count)

    # --------------------------------------------------
    # FEATURE EXTRACTION
    # --------------------------------------------------
    def get_features(self, solution_type="balanced"):
        if solution_type == "best_accuracy":
            idx = np.argmin([f[0] for f in self.pareto_fitness_])
        elif solution_type == "best_efficiency":
            idx = np.argmin([f[1] for f in self.pareto_fitness_])
        else:
            score = [(1 - f[1]) / f[0] for f in self.pareto_fitness_]
            idx = np.argmax(score)

        stage2_idx = np.where(self.pareto_front_[idx] == 1)[0]
        return self.selected_stage1_[stage2_idx]

    def transform(self, X, solution_type="balanced"):
        return X[:, self.get_features(solution_type)]

if __name__ == "__main__":

    np.random.seed(42)
    n_samples, n_features = 1000, 50

    X = np.random.randn(n_samples, n_features)

    # True MPPT-like target depends on first 5 features
    y = (
        2.0 * X[:, 0]
        + 1.5 * X[:, 1]
        - 1.0 * X[:, 2]
        + 0.8 * X[:, 3]
        + 0.5 * X[:, 4]
        + np.random.normal(0, 0.5, n_samples)
    )

    print("Dataset:", X.shape)

    model = MI_AMO_BHS(
        beta=0.6,
        hms=10,
        max_iter=50,
        n_min=3,
        n_max=20,
        random_state=42
    )

    model.fit(X, y, verbose=1)

    selected = model.get_features("balanced")
    print("\nSelected features:", sorted(selected))
    print("Recovered all true features (0–4):",
          set(range(5)).issubset(set(selected)))

# ADD THESE IN __init__()
self.history_ = {
    "mi_scores": None,
    "rmse_curve": [],
    "feature_ratio_curve": [],
    "pareto_size": [],
    "diversity": []
}

self.history_["mi_scores"] = mi_scores.copy()

best_rmse = min(f[0] for f in fitness)
avg_ratio = np.mean([f[1] for f in fitness])

# Population diversity (novel contribution)
diversity = np.mean([
    np.sum(h1 != h2)
    for h1 in HM
    for h2 in HM
]) / (HM.shape[0] * HM.shape[1])

self.history_["rmse_curve"].append(best_rmse)
self.history_["feature_ratio_curve"].append(avg_ratio)
self.history_["pareto_size"].append(len(self.pareto_front_) if hasattr(self, "pareto_front_") else 0)
self.history_["diversity"].append(diversity)

import matplotlib.pyplot as plt
import scipy.stats as stats

def plot_mi_distribution(mi_scores, title):
    plt.figure(figsize=(10,6))
    plt.hist(mi_scores, bins=30, density=True, alpha=0.7)
    plt.xlabel("Mutual Information Score")
    plt.ylabel("Density")
    plt.title(title)
    plt.grid(True)
    plt.show()

    print("MI Statistics")
    print("Min:", np.min(mi_scores))
    print("Max:", np.max(mi_scores))
    print("Mean:", np.mean(mi_scores))
    print("Std:", np.std(mi_scores))
    print("Skewness:", stats.skew(mi_scores))
    print("Kurtosis:", stats.kurtosis(mi_scores))

def plot_top_mi_features(mi_scores, top_k=15):
    idx = np.argsort(mi_scores)[::-1][:top_k]
    plt.figure(figsize=(10,5))
    plt.bar(range(top_k), mi_scores[idx])
    plt.xticks(range(top_k), idx, rotation=45)
    plt.ylabel("MI Score")
    plt.title("Top-Ranked Features by MI")
    plt.grid(True)
    plt.show()

from sklearn.ensemble import RandomForestRegressor

def plot_mi_vs_importance(X, y, mi_scores):
    rf = RandomForestRegressor(n_estimators=200, random_state=42)
    rf.fit(X, y)
    importance = rf.feature_importances_

    plt.figure(figsize=(7,6))
    plt.scatter(mi_scores, importance)
    plt.xlabel("Mutual Information Score")
    plt.ylabel("RF Feature Importance")
    plt.title("MI vs Feature Importance Correlation")
    plt.grid(True)
    plt.show()

    corr = np.corrcoef(mi_scores, importance)[0,1]
    print("Pearson correlation:", corr)

def plot_convergence(history):
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.plot(history["rmse_curve"])
    plt.title("RMSE Convergence")
    plt.xlabel("Iteration")
    plt.ylabel("RMSE")

    plt.subplot(1,3,2)
    plt.plot(history["pareto_size"])
    plt.title("Pareto Set Growth")
    plt.xlabel("Iteration")
    plt.ylabel("Pareto Size")

    plt.subplot(1,3,3)
    plt.plot(history["diversity"])
    plt.title("Population Diversity")
    plt.xlabel("Iteration")
    plt.ylabel("Diversity")

    plt.tight_layout()
    plt.show()

def plot_convergence_efficiency(history):
    improvement = np.abs(np.diff(history["rmse_curve"]))
    plt.figure(figsize=(8,5))
    plt.plot(improvement)
    plt.xlabel("Iteration")
    plt.ylabel("Fitness Improvement Rate")
    plt.title("Convergence Efficiency")
    plt.grid(True)
    plt.show()

def plot_rmse_vs_features(pareto_fitness):
    rmse = [f[0] for f in pareto_fitness]
    ratio = [f[1] for f in pareto_fitness]

    plt.figure(figsize=(7,6))
    plt.scatter(ratio, rmse, c=ratio, cmap="viridis")
    plt.xlabel("Feature Ratio")
    plt.ylabel("RMSE")
    plt.title("RMSE vs Feature Density Trade-off")
    plt.colorbar(label="Feature Ratio")
    plt.grid(True)
    plt.show()

def plot_performance_bar(results):
    plt.figure(figsize=(8,5))
    plt.bar(results.keys(), results.values())
    plt.ylabel("RMSE")
    plt.title("Cross-Dataset Performance Comparison")
    plt.grid(True)
    plt.show()

model = MI_AMO_BHS(beta=0.6, hms=20, max_iter=100, n_min=5)
model.fit(X, y, verbose=1)

plot_mi_distribution(model.history_["mi_scores"], "MI Score Distribution")
plot_top_mi_features(model.history_["mi_scores"])
plot_mi_vs_importance(X, y, model.history_["mi_scores"])

plot_convergence(model.history_)
plot_convergence_efficiency(model.history_)
plot_rmse_vs_features(model.pareto_fitness_)

